server:
  port: 9003

spring:
  application:
    name: product-service
  datasource:
    url: jdbc:mysql://localhost:3306/myecommerce?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: Abhaymurali2004
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  data:
    redis:
      host: localhost
      port: 6380

jwt:
  secret: ecommerceSecretKey2026SuperSecureJwtTokenForAuthenticationAndAuthorization

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

logging:
  file:
    name: product-service.log
  level:
    org.springframework.web: DEBUG
    com.ecommerceproject.product: DEBUG
    root: INFO
